### PR TITLE
Removed rvmrc and started on Debian build instructions

### PR DESCRIPTION
**Pull request by pjotrp**

### CODE REVIEW

**Comment by pjotrp** [comment]
I did not succeed on building kyoto cabinet on Debian. The errors I am getting, even following the packager instructions are

git diff
diff --git a/configure b/configure
index a07063d..0cf92c8 100755
--- a/configure
+++ b/configure
@@ -3991,8 +3991,8 @@ then
   printf 'checking for CPU optimization availability... '
   if printf 'main() {}' | $CC -xc -march=native -o config.tmp - >config.tmp 2>&1
   then
-    MYCFLAGS="-march=native $MYCFLAGS"
-    MYCXXFLAGS="-march=native $MYCXXFLAGS"
-    # MYCFLAGS="-march=native $MYCFLAGS"
-    # MYCXXFLAGS="-march=native $MYCXXFLAGS"
   printf 'yes\n'
  else
   printf 'no\n'

./configure --enable-zlib --enable-lzo --enable-lzma --prefix=/usr --disable-atomic
make prefix=/usr

/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/liblzma.so when searching for -llzma
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/liblzma.a when searching for -llzma
/usr/bin/ld: cannot find -llzma
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/gcc/i486-linux-gnu/4.5.3/../../../liblzo2.so when searching for -llzo2
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/gcc/i486-linux-gnu/4.5.3/../../../liblzo2.a when searching for -llzo2
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/liblzo2.so when searching for -llzo2
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/liblzo2.a when searching for -llzo2
/usr/bin/ld: cannot find -llzo2
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/gcc/i486-linux-gnu/4.5.3/../../../libz.so when searching for -lz
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/gcc/i486-linux-gnu/4.5.3/../../../libz.a when searching for -lz
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/libz.so when searching for -lz
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/libz.a when searching for -lz
/usr/bin/ld: cannot find -lz
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/gcc/i486-linux-gnu/4.5.3/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/gcc/i486-linux-gnu/4.5.3/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
collect2: ld returned 1 exit status
make: **\* [libkyotocabinet.so.16.13.0] Error 1

on

venezia:~/izip/doc/Programming$ cat /proc/version 
Linux version 3.2.0-2-686-pae (Debian 3.2.19-1) (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-7) ) #1 SMP Fri Jun 1 18:56:14 UTC 2012
venezia:~/izip/doc/Programming$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i486-linux-gnu/4.6/lto-wrapper
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.6.3-1' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++,go --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-plugin --enable-objc-gc --enable-targets=all --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.6.3 (Debian 4.6.3-1) 

Missing something :/

**Comment by csw** [comment]
Attempting to reproduce this Debian install issue. This is Debian testing (wheezy) 32-bit, right?

**Comment by csw** [comment]
Okay, I've come up with detailed Kyoto Cabinet [installation instructions](https://github.com/csw/bioruby-maf/wiki/Kyoto-Cabinet) on the wiki for Debian wheezy 32-bit. Should work for 64-bit too. I may keep this stuff on the wiki to avoid README.md becoming totally bloated.

**Comment by csw** [comment]
Now have KC installation instructions for Mac OS X, Ubuntu, Debian, and Fedora.

**Comment by pjotrp** [comment]
The build is still not working on my Debian (a mixture of stable and testing). Getting the same incompatible libz and libstd++ errors. I'll try again next week on a different machine.

**Comment by csw** [comment]
Interesting. I think I see what's going on, though. `gcc -v` reports that you're using GCC 4.6, but those link errors indicate that you're picking up a version of libstdc++ from GCC 4.5. If you don't have anything depending on them, it might be worth trying to remove those old library versions. There might be some other kind of linker trick you could use, too. Also, you'd be safe building it without the explicit configure arguments, just `./configure && make`, I think.

**Pull request merged**
